name: NitroPlate
main: net.azisaba.nitroplate.NitroPlate
version: ${version}
depend:
  - AziPluginMessaging
commands:
  setprefix:
    permission: nitroplate.setprefix
  setglobalprefix:
    permission: nitroplate.setglobalprefix
  clearprefix:
    permission: nitroplate.clearprefix
  clearglobalprefix:
    permission: nitroplate.clearglobalprefix
  togglenitro:
    permission: nitroplate.togglenitro
